###############################################################################
#  In settings.py:
#       DATABASES = {
    #     "default": {
    #         "ENGINE": "django.db.backends.postgresql",
    #         "NAME": "docker-drf",
    #         "USER": os.getenv("DOCKER_DJANGO_DATABASE_USER"),
    #         "PASSWORD": os.getenv("DOCKER_DJANGO_DATABASE_PASSWORD", ""),
    #         "HOST": os.getenv("DOCKER_DJANGO_DATABASE_HOST", "localhost"),
    #         "PORT": os.getenv("DOCKER_DJANGO_DATABASE_PORT", "5432"),
    #     }
    # }
#
###############################################################################
version: "3.1"

volumes:
    db-data:

services:

    django:
      build: ./docker/django
      container_name: ${PROJECT_NAME}-django
      command: python3 manage.py runserver 0.0.0.0:7400
      volumes:
        - .:/application
      ports:
        - "7400:7400"
      depends_on:
        - db

    db:
      image: postgres
      volumes:
        - db-data:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - "8306:3306"